In [4]:
!pip install torch torchvision

In [16]:
import torch
import torch.nn.functional as F
import torch.nn as nn
import torch.nn.init as init
import numpy as np 

In [25]:
t1 =torch.Tensor(4,5)
t1.size()
# print(t1.size())

torch.Size([4, 5])

In [26]:
t2 = torch.Tensor([3.2, 4.3, 5.5])

In [27]:
t3 = torch.Tensor(np.array([[3.2], [4.3], [5.5]]))

In [28]:
t4 = torch.rand(4,6)

In [30]:
t5 = t1 + t2

RuntimeError: The size of tensor a (5) must match the size of tensor b (3) at non-singleton dimension 1

In [32]:
# Variable is in the autograd module
from torch.autograd import Variable
# Variables wrap tensors
x = Variable(torch.Tensor([1, 2, 3]), requires_grad=True)
# You can access the underlying tensor with the .data attribute
print(x.data)
# Any operation you could use on Tensors, you can use
# on Variables. Operations between Variables produce
# Variables.
y = Variable(torch.Tensor([4, 5, 6]), requires_grad=True)
z = x + y
print(z.data)
# z knows its function to compute gradient.
print(z.grad_fn) # Magic of auto differentiation.

tensor([1., 2., 3.])
tensor([5., 7., 9.])


In [33]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)
c = 3
print(c*x)

tensor([[0.0637, 2.3304, 0.6797, 0.1758],
        [2.0646, 2.8213, 2.7790, 2.1455],
        [1.8222, 1.5114, 1.7032, 1.6941],
        [2.6598, 1.9846, 1.7060, 0.7954],
        [2.1811, 1.3909, 2.2920, 0.3170]])


In [34]:
x+y

tensor([[0.1440, 1.4238, 0.3242, 0.3095],
        [1.4121, 1.7437, 1.2543, 1.3014],
        [1.3702, 1.0841, 0.9645, 0.8047],
        [1.8505, 0.9963, 0.5983, 0.7293],
        [1.5529, 1.3374, 1.1102, 0.3609]])

In [35]:
x.add(y)

tensor([[0.1440, 1.4238, 0.3242, 0.3095],
        [1.4121, 1.7437, 1.2543, 1.3014],
        [1.3702, 1.0841, 0.9645, 0.8047],
        [1.8505, 0.9963, 0.5983, 0.7293],
        [1.5529, 1.3374, 1.1102, 0.3609]])

In [36]:
torch.cuda.is_available()

/home/saugat/Desktop/NLP/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0


False

In [37]:
a = torch.rand(5, 4)
a = a.cuda()
print(a)

RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination

In [38]:
from torch.autograd import Variable

In [39]:
# requires_grad
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4

In [40]:
z.backward()

In [41]:
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: tensor([2.])
dz/dy: tensor([1.])


In [42]:
from torch import nn
import torch.nn.functional as F

In [43]:
class Model(nn.Module):
    def  __init__(self):
        super(Model , self).__init__()
        self.conv1 = nn.Conv2d(3,10,3)
    
    def forward(self,x):
        out = self.con1(x)
        return out